
services:

  app:
    build:
      target: dev
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:8082/.well-known/mercure
      MERCURE_JWT_SECRET: "!ChangeMercureHubJWTSecretKey!"

  nginx:
    depends_on:
      - app
  database:
    ports:
      - "5433:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
