<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260729000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Migrer statut_reservation et statut_paiement de tables FK vers colonnes enum string';
    }

    public function up(Schema $schema): void
    {
        // ── reservation ──────────────────────────────────────────────────────────
        $this->addSql("ALTER TABLE reservation ADD COLUMN statut_reservation VARCHAR(50) NOT NULL DEFAULT 'en_attente'");
        // Migrer les données existantes depuis la table de référence
        $this->addSql("
            UPDATE reservation r
            SET statut_reservation = COALESCE(
                (SELECT label_statut_reservation FROM statut_reservation sr WHERE sr.id = r.statut_reservation_id),
                'en_attente'
            )
        ");
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT IF EXISTS FK_42C84955C583C008');
        $this->addSql('DROP INDEX IF EXISTS IDX_42C84955C583C008');
        $this->addSql('DROP INDEX IF EXISTS idx_reservation_statut');
        $this->addSql('ALTER TABLE reservation DROP COLUMN statut_reservation_id');

        // ── paiement ─────────────────────────────────────────────────────────────
        $this->addSql("ALTER TABLE paiement ADD COLUMN statut_paiement VARCHAR(50) NOT NULL DEFAULT 'en_attente'");
        // Migrer les données existantes depuis la table de référence
        $this->addSql("
            UPDATE paiement p
            SET statut_paiement = COALESCE(
                (SELECT label_statut_paiement FROM statut_paiement sp WHERE sp.id = p.statut_paiement_ref_id),
                'en_attente'
            )
        ");
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT IF EXISTS FK_B1DC7A1E9CDF9A07');
        $this->addSql('DROP INDEX IF EXISTS IDX_B1DC7A1E9CDF9A07');
        $this->addSql('ALTER TABLE paiement DROP COLUMN statut_paiement_ref_id');

        // ── supprimer les tables devenues inutiles ────────────────────────────────
        $this->addSql('DROP TABLE statut_reservation');
        $this->addSql('DROP TABLE statut_paiement');
    }

    public function down(Schema $schema): void
    {
        // Recréer les tables
        $this->addSql("CREATE TABLE statut_reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_statut_reservation VARCHAR(150) NOT NULL UNIQUE, PRIMARY KEY (id))");
        $this->addSql("CREATE TABLE statut_paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_statut_paiement VARCHAR(50) NOT NULL UNIQUE, PRIMARY KEY (id))");

        // Réinsérer les valeurs de référence
        $this->addSql("INSERT INTO statut_reservation (label_statut_reservation) VALUES ('en_attente'), ('confirmée'), ('annulée'), ('refusée'), ('terminée')");
        $this->addSql("INSERT INTO statut_paiement (label_statut_paiement) VALUES ('en_attente'), ('payé'), ('échoué'), ('remboursé')");

        // Restaurer la colonne FK sur reservation
        $this->addSql('ALTER TABLE reservation ADD COLUMN statut_reservation_id INT');
        $this->addSql("UPDATE reservation r SET statut_reservation_id = (SELECT id FROM statut_reservation sr WHERE sr.label_statut_reservation = r.statut_reservation)");
        $this->addSql('ALTER TABLE reservation ALTER COLUMN statut_reservation_id SET NOT NULL');
        $this->addSql('ALTER TABLE reservation DROP COLUMN statut_reservation');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955C583C008 FOREIGN KEY (statut_reservation_id) REFERENCES statut_reservation (id) NOT DEFERRABLE');

        // Restaurer la colonne FK sur paiement
        $this->addSql('ALTER TABLE paiement ADD COLUMN statut_paiement_ref_id INT');
        $this->addSql("UPDATE paiement p SET statut_paiement_ref_id = (SELECT id FROM statut_paiement sp WHERE sp.label_statut_paiement = p.statut_paiement)");
        $this->addSql('ALTER TABLE paiement ALTER COLUMN statut_paiement_ref_id SET NOT NULL');
        $this->addSql('ALTER TABLE paiement DROP COLUMN statut_paiement');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E9CDF9A07 FOREIGN KEY (statut_paiement_ref_id) REFERENCES statut_paiement (id) NOT DEFERRABLE');
    }
}
