<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260606100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace role table with JSON roles column on utilisateur';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE utilisateur ADD COLUMN roles JSON NOT NULL DEFAULT \'["ROLE_USER"]\'');
        $this->addSql('ALTER TABLE utilisateur ALTER COLUMN roles DROP DEFAULT');
        $this->addSql('ALTER TABLE utilisateur_role DROP CONSTRAINT FK_9EE8E650FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_role DROP CONSTRAINT FK_9EE8E650D60322AC');
        $this->addSql('DROP TABLE utilisateur_role');
        $this->addSql('DROP TABLE role');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_role VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE utilisateur_role (utilisateur_id BIGINT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (utilisateur_id, role_id))');
        $this->addSql('CREATE INDEX IDX_9EE8E650FB88E14F ON utilisateur_role (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_9EE8E650D60322AC ON utilisateur_role (role_id)');
        $this->addSql('ALTER TABLE utilisateur_role ADD CONSTRAINT FK_9EE8E650FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_role ADD CONSTRAINT FK_9EE8E650D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur DROP COLUMN roles');
    }
}
