<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260605165249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assurance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, prix NUMERIC(15, 2) NOT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE avis (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, commentaire TEXT NOT NULL, date_avis TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F91ABF0FB88E14F ON avis (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_8F91ABF0B83297E7 ON avis (reservation_id)');
        $this->addSql('CREATE TABLE bateau (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_bateau VARCHAR(255) NOT NULL, motorisation VARCHAR(255) NOT NULL, capacite INT DEFAULT NULL, taille VARCHAR(50) NOT NULL, avec_skipper BOOLEAN NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(50) NOT NULL, prix_jour NUMERIC(20, 2) NOT NULL, prix_heure NUMERIC(15, 2) DEFAULT NULL, port_id INT NOT NULL, proprietaire_id BIGINT NOT NULL, type_bateau_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A664B05A76E92A9C ON bateau (port_id)');
        $this->addSql('CREATE INDEX IDX_A664B05A76C50E4A ON bateau (proprietaire_id)');
        $this->addSql('CREATE INDEX IDX_A664B05A1DB62419 ON bateau (type_bateau_id)');
        $this->addSql('CREATE TABLE contrat (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conditions TEXT NOT NULL, assurance_incluse BOOLEAN NOT NULL, statut_contrat VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE disponibilite (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR(50) NOT NULL, bateau_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2CBACE2FA9706509 ON disponibilite (bateau_id)');
        $this->addSql('CREATE TABLE document (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url_document TEXT NOT NULL, date_upload TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type_document_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A768826AFA6 ON document (type_document_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, lu BOOLEAN NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_utilisateur BIGINT NOT NULL, id_utilisateur_1 BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F50EAE44 ON message (id_utilisateur)');
        $this->addSql('CREATE INDEX IDX_B6BD307F885F52BE ON message (id_utilisateur_1)');
        $this->addSql('CREATE TABLE mode_de_paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_mode_paiement VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE paiement (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_paiement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, montant NUMERIC(20, 2) NOT NULL, statut_paiement VARCHAR(50) NOT NULL, statut_paiement_ref_id INT NOT NULL, mode_paiement_id INT NOT NULL, reservation_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E9CDF9A07 ON paiement (statut_paiement_ref_id)');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E438F5B63 ON paiement (mode_paiement_id)');
        $this->addSql('CREATE INDEX IDX_B1DC7A1EB83297E7 ON paiement (reservation_id)');
        $this->addSql('CREATE TABLE photo_bateau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url TEXT NOT NULL, description VARCHAR(255) DEFAULT NULL, ordre_affichage INT DEFAULT NULL, bateau_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3DBC772A9706509 ON photo_bateau (bateau_id)');
        $this->addSql('CREATE TABLE port (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, pays VARCHAR(150) NOT NULL, ville VARCHAR(150) NOT NULL, code_postal VARCHAR(20) DEFAULT NULL, latitude TEXT DEFAULT NULL, longitude TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reservation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_reservation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, montant_total NUMERIC(20, 2) NOT NULL, contrat_id BIGINT NOT NULL, bateau_id BIGINT NOT NULL, statut_reservation_id INT NOT NULL, utilisateur_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42C849551823061F ON reservation (contrat_id)');
        $this->addSql('CREATE INDEX IDX_42C84955A9706509 ON reservation (bateau_id)');
        $this->addSql('CREATE INDEX IDX_42C84955C583C008 ON reservation (statut_reservation_id)');
        $this->addSql('CREATE INDEX IDX_42C84955FB88E14F ON reservation (utilisateur_id)');
        $this->addSql('CREATE TABLE reservation_assurance (reservation_id BIGINT NOT NULL, assurance_id INT NOT NULL, PRIMARY KEY (reservation_id, assurance_id))');
        $this->addSql('CREATE INDEX IDX_222F4831B83297E7 ON reservation_assurance (reservation_id)');
        $this->addSql('CREATE INDEX IDX_222F4831B288C3E3 ON reservation_assurance (assurance_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_role VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE statut_paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_statut_paiement VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CEDAC6BFFA0B0B17 ON statut_paiement (label_statut_paiement)');
        $this->addSql('CREATE TABLE statut_reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_statut_reservation VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE type_bateau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_type_bateau VARCHAR(155) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE type_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_type_document VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE utilisateur (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, mot_de_passe VARCHAR(255) NOT NULL, telephone VARCHAR(50) DEFAULT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut_compte VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql('CREATE TABLE utilisateur_role (utilisateur_id BIGINT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (utilisateur_id, role_id))');
        $this->addSql('CREATE INDEX IDX_9EE8E650FB88E14F ON utilisateur_role (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_9EE8E650D60322AC ON utilisateur_role (role_id)');
        $this->addSql('CREATE TABLE document_utilisateur (utilisateur_id BIGINT NOT NULL, document_id BIGINT NOT NULL, PRIMARY KEY (utilisateur_id, document_id))');
        $this->addSql('CREATE INDEX IDX_9FB554D9FB88E14F ON document_utilisateur (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_9FB554D9C33F7837 ON document_utilisateur (document_id)');
        $this->addSql('CREATE TABLE favoris (utilisateur_id BIGINT NOT NULL, bateau_id BIGINT NOT NULL, PRIMARY KEY (utilisateur_id, bateau_id))');
        $this->addSql('CREATE INDEX IDX_8933C432FB88E14F ON favoris (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_8933C432A9706509 ON favoris (bateau_id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bateau ADD CONSTRAINT FK_A664B05A76E92A9C FOREIGN KEY (port_id) REFERENCES port (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bateau ADD CONSTRAINT FK_A664B05A76C50E4A FOREIGN KEY (proprietaire_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bateau ADD CONSTRAINT FK_A664B05A1DB62419 FOREIGN KEY (type_bateau_id) REFERENCES type_bateau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disponibilite ADD CONSTRAINT FK_2CBACE2FA9706509 FOREIGN KEY (bateau_id) REFERENCES bateau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A768826AFA6 FOREIGN KEY (type_document_id) REFERENCES type_document (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F885F52BE FOREIGN KEY (id_utilisateur_1) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E9CDF9A07 FOREIGN KEY (statut_paiement_ref_id) REFERENCES statut_paiement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E438F5B63 FOREIGN KEY (mode_paiement_id) REFERENCES mode_de_paiement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_bateau ADD CONSTRAINT FK_F3DBC772A9706509 FOREIGN KEY (bateau_id) REFERENCES bateau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849551823061F FOREIGN KEY (contrat_id) REFERENCES contrat (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A9706509 FOREIGN KEY (bateau_id) REFERENCES bateau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955C583C008 FOREIGN KEY (statut_reservation_id) REFERENCES statut_reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_assurance ADD CONSTRAINT FK_222F4831B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation_assurance ADD CONSTRAINT FK_222F4831B288C3E3 FOREIGN KEY (assurance_id) REFERENCES assurance (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_role ADD CONSTRAINT FK_9EE8E650FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_role ADD CONSTRAINT FK_9EE8E650D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_utilisateur ADD CONSTRAINT FK_9FB554D9FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_utilisateur ADD CONSTRAINT FK_9FB554D9C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C432FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C432A9706509 FOREIGN KEY (bateau_id) REFERENCES bateau (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0FB88E14F');
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0B83297E7');
        $this->addSql('ALTER TABLE bateau DROP CONSTRAINT FK_A664B05A76E92A9C');
        $this->addSql('ALTER TABLE bateau DROP CONSTRAINT FK_A664B05A76C50E4A');
        $this->addSql('ALTER TABLE bateau DROP CONSTRAINT FK_A664B05A1DB62419');
        $this->addSql('ALTER TABLE disponibilite DROP CONSTRAINT FK_2CBACE2FA9706509');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A768826AFA6');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F50EAE44');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F885F52BE');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E9CDF9A07');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E438F5B63');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1EB83297E7');
        $this->addSql('ALTER TABLE photo_bateau DROP CONSTRAINT FK_F3DBC772A9706509');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849551823061F');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955A9706509');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955C583C008');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955FB88E14F');
        $this->addSql('ALTER TABLE reservation_assurance DROP CONSTRAINT FK_222F4831B83297E7');
        $this->addSql('ALTER TABLE reservation_assurance DROP CONSTRAINT FK_222F4831B288C3E3');
        $this->addSql('ALTER TABLE utilisateur_role DROP CONSTRAINT FK_9EE8E650FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_role DROP CONSTRAINT FK_9EE8E650D60322AC');
        $this->addSql('ALTER TABLE document_utilisateur DROP CONSTRAINT FK_9FB554D9FB88E14F');
        $this->addSql('ALTER TABLE document_utilisateur DROP CONSTRAINT FK_9FB554D9C33F7837');
        $this->addSql('ALTER TABLE favoris DROP CONSTRAINT FK_8933C432FB88E14F');
        $this->addSql('ALTER TABLE favoris DROP CONSTRAINT FK_8933C432A9706509');
        $this->addSql('DROP TABLE assurance');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE bateau');
        $this->addSql('DROP TABLE contrat');
        $this->addSql('DROP TABLE disponibilite');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE mode_de_paiement');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE photo_bateau');
        $this->addSql('DROP TABLE port');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE reservation_assurance');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE statut_paiement');
        $this->addSql('DROP TABLE statut_reservation');
        $this->addSql('DROP TABLE type_bateau');
        $this->addSql('DROP TABLE type_document');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_role');
        $this->addSql('DROP TABLE document_utilisateur');
        $this->addSql('DROP TABLE favoris');
    }
}
