<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260806000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des tables type_equipement, equipement et du pivot bateau_equipement';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE type_equipement (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            label_type_equipement VARCHAR(100) NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uq_label_type_equipement ON type_equipement (label_type_equipement)');

        $this->addSql('CREATE TABLE equipement (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            type_equipement_id INT NOT NULL,
            nom VARCHAR(150) NOT NULL,
            icone VARCHAR(100) DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uq_nom_equipement ON equipement (nom)');
        $this->addSql('CREATE INDEX IDX_equipement_type ON equipement (type_equipement_id)');
        $this->addSql('ALTER TABLE equipement ADD CONSTRAINT FK_equipement_type FOREIGN KEY (type_equipement_id) REFERENCES type_equipement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE bateau_equipement (
            bateau_id BIGINT NOT NULL,
            equipement_id INT NOT NULL,
            PRIMARY KEY (bateau_id, equipement_id)
        )');
        $this->addSql('CREATE INDEX IDX_bateau_equipement_bateau ON bateau_equipement (bateau_id)');
        $this->addSql('CREATE INDEX IDX_bateau_equipement_equipement ON bateau_equipement (equipement_id)');
        $this->addSql('ALTER TABLE bateau_equipement ADD CONSTRAINT FK_bateau_equipement_bateau FOREIGN KEY (bateau_id) REFERENCES bateau (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bateau_equipement ADD CONSTRAINT FK_bateau_equipement_equipement FOREIGN KEY (equipement_id) REFERENCES equipement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Données référentielles — types
        $this->addSql("INSERT INTO type_equipement (label_type_equipement) VALUES
            ('Navigation'),
            ('Sécurité'),
            ('Confort & Hébergement'),
            ('Cuisine'),
            ('Communication & Électronique'),
            ('Loisirs & Activités nautiques')
        ");

        // Données référentielles — équipements
        $this->addSql("INSERT INTO equipement (type_equipement_id, nom, icone) VALUES
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'GPS / Chartplotter',   'fa-location-dot'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'Compas',               'fa-compass'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'Sondeur',              'fa-water'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'Pilote automatique',   'fa-robot'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'Jumelles',             'fa-binoculars'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'Anémomètre',           'fa-wind'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'Cartes marines',       'fa-map'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Navigation'), 'AIS',                  'fa-satellite-dish'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Gilets de sauvetage adulte',  'fa-life-ring'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Gilets de sauvetage enfant',  'fa-child'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Balise EPIRB',                'fa-satellite'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Fusées de détresse',          'fa-fire'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Extincteur',                  'fa-fire-extinguisher'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Radeau de survie',            'fa-shield-halved'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Trousse de premiers secours', 'fa-kit-medical'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Harnais de sécurité',         'fa-person'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Pompe de cale',               'fa-arrow-up-from-water-pump'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Ancre',                       'fa-anchor'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Sécurité'), 'Coupe-circuit moteur',        'fa-plug-circle-xmark'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Climatisation',              'fa-snowflake'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Chauffage',                  'fa-temperature-high'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Draps et literie',           'fa-bed'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Serviettes',                 'fa-shirt'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Bimini (protection soleil)', 'fa-umbrella-beach'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Douche extérieure',          'fa-shower'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'WC de bord',                 'fa-toilet'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Eau chaude',                 'fa-droplet'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Moustiquaires',              'fa-shield'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Confort & Hébergement'), 'Ventilateurs',               'fa-fan'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Cuisinière à gaz',    'fa-fire-burner'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Réfrigérateur',       'fa-temperature-low'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Four / Micro-ondes',  'fa-bolt'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Barbecue de bord',    'fa-fire'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Vaisselle complète',  'fa-utensils'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Batterie de cuisine', 'fa-utensils'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Cafetière',           'fa-mug-hot'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Cuisine'), 'Glacière',            'fa-box'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Communication & Électronique'), 'VHF fixe',        'fa-radio'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Communication & Électronique'), 'VHF portable',    'fa-mobile-screen'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Communication & Électronique'), 'WiFi à bord',     'fa-wifi'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Communication & Électronique'), 'Prises 220V',     'fa-plug'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Communication & Électronique'), 'Panneau solaire', 'fa-solar-panel'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Communication & Électronique'), 'TV / Écran',      'fa-tv'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Paddle (SUP)',           'fa-person-swimming'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Kayak',                  'fa-person-rowing'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Masque et tuba',         'fa-mask'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Équipement de plongée',  NULL),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Bouée tractée',          'fa-circle'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Ski nautique',           NULL),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Canne à pêche',          'fa-fish'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Annexe (dinghy)',        'fa-sailboat'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Hors-bord annexe',       'fa-gear'),
            ((SELECT id FROM type_equipement WHERE label_type_equipement = 'Loisirs & Activités nautiques'), 'Tapis de bain',          NULL)
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE bateau_equipement DROP CONSTRAINT FK_bateau_equipement_bateau');
        $this->addSql('ALTER TABLE bateau_equipement DROP CONSTRAINT FK_bateau_equipement_equipement');
        $this->addSql('DROP TABLE bateau_equipement');
        $this->addSql('ALTER TABLE equipement DROP CONSTRAINT FK_equipement_type');
        $this->addSql('DROP TABLE equipement');
        $this->addSql('DROP TABLE type_equipement');
    }
}
